export const darkTheme = {
  bodyBackgroundColor: '#1e1e1e',
  appBackgroundColor: '#181818',
  controlBackgroundColor: '#181818',
  imgTextColor: '#D7D7D7',
  calendarBackgroundColor: '#303030',
  calendarColor: '#89aaff',
  calendarDayColor: '#89aaff',
  calendarNowBackground: '#5a89ff53',
  mainColor: '#5A88FF',
  inputBackground: '#89aaff67',
  circleStroke: '#3A5BAE',
  childCircleStroke: '#e7e7e781',
  iconColor: '#6062fb',
  iconActiveColor: '#6062fb83',
  modeBtnBackgroundColor: '#1e1f22',
  modalTextColor: '#f7f7f7d3',
  paginationBtnColor: '#5A88FF',
  paginationListColor: '#f1f1f1',
  paginationBackgroundColor: '#dddddd6',
  graphColor: '#89aaff',
  footerBackgroundColor: '#1e1f22',
  textColor: '#D7D7D7',
  modalBackgroundColor: '#303030',
  todayGraphBackground: '#181818',
  headerBackground: '#1e1f22',
};
export const lightTheme = {
  bodyBackgroundColor: '#f6f6f6',
  appBackgroundColor: '#f2f2f2',
  controlBackgroundColor: '#fff',
  imgTextColor: '#303030',
  calendarBackgroundColor: '#fff7dab0',
  calendarColor: '#A65D50',
  calendarDayColor: '#ec9788',
  calendarNowBackground: '#ff595657',
  mainColor: '#ff5a5a',
  inputBackground: '#ffcece',
  textColor: '#5f3b3b',
  circleStroke: '#FF5A5A',
  childCircleStroke: '#F2B5AA',
  iconColor: '#ff5953',
  iconActiveColor: '#943737',
  modeBtnBackgroundColor: '#EDEDED',
  modalBackgroundColor: '#fff7da',
  footerBackgroundColor: '#EDEDED',
  paginationBtnColor: '#f14747',
  paginationListColor: '#333',
  paginationBackgroundColor: '#fff',
  graphColor: '#5F3B3B',
  modalTextColor: '#303030',
  todayGraphBackground: 'white',
  headerBackground: '#EDEDED',

};